management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  profiles:
    active:
#    - dblocal
#    - redislocal
#    - tomcatlocal
    - loglocal
    - dbReal
    - redisReal
    - tomcatReal

  application:
    name: luna-admin
  jackson:
    default-property-inclusion: NON_NULL

mybatis:
  type-aliases-package: kr.co.lunasoft.batchadmin.vo

# dblocal 환경
# mslocal 환경
---
spring:
  profiles: dblocal

  mongodb:
    uri: mongodb://team-core:HappyEnding201910!@test-log.cluster-cghtjgokrsze.ap-northeast-2.docdb.amazonaws.com:27017

  dbmall:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://test-cluster.cluster-ro-cghtjgokrsze.ap-northeast-2.rds.amazonaws.com:3306/?&autoReconnect=true&verifyServerCertificate=false&useSSL=false
        username: brian
        password: brian01076225850
        driverClassName: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 10
        #minimum-idle: 100
        max-lifetime: 1800000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

  dbmallWrite:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://test-cluster.cluster-cghtjgokrsze.ap-northeast-2.rds.amazonaws.com:3306/?&autoReconnect=true&verifyServerCertificate=false&useSSL=false
        username: brian
        password: brian01076225850
        driverClassName: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 10
        #minimum-idle: 100
        max-lifetime: 1800000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

  dbadmin:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://test-cluster.cluster-cghtjgokrsze.ap-northeast-2.rds.amazonaws.com:3306?&autoReconnect=true&verifyServerCertificate=false&useSSL=false
        username: brian
        password: brian01076225850
        driverClassName: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 10
        #minimum-idle: 100
        max-lifetime: 1800000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

  dbadminWrite:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://test-cluster.cluster-cghtjgokrsze.ap-northeast-2.rds.amazonaws.com:3306?&autoReconnect=true&verifyServerCertificate=false&useSSL=false
        username: brian
        password: brian01076225850
        driverClassName: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 10
        #minimum-idle: 100
        max-lifetime: 1800000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

# dbReal 환경
---
spring:
  profiles: dbReal

  mongodb:
    uri: mongodb://team-core:WlsWkdlfgkrltlfgek!@prod-log.cluster-cghtjgokrsze.ap-northeast-2.docdb.amazonaws.com:5637

  dbmall:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://production-rds-mall.cluster-ro-cghtjgokrsze.ap-northeast-2.rds.amazonaws.com:56375/?&autoReconnect=true&verifyServerCertificate=false&useSSL=false
        username: admin-mall
        password: lunaAdminMall201906!
        driverClassName: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 50
        #minimum-idle: 100
        max-lifetime: 60000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true


  dbmallWrite:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://production-rds-mall.cluster-cghtjgokrsze.ap-northeast-2.rds.amazonaws.com:56375/?&autoReconnect=true&verifyServerCertificate=false&useSSL=false
        username: admin-mall
        password: lunaAdminMall201906!
        driverClassName: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 50
        #minimum-idle: 100
        max-lifetime: 60000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true


  dbadmin:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://production-rds-admin.cluster-ro-cghtjgokrsze.ap-northeast-2.rds.amazonaws.com:56375?&autoReconnect=true&verifyServerCertificate=false&useSSL=false
        username: admin-base
        password: lunaAdminBase201906!
        driverClassName: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 30
        #minimum-idle: 100
        max-lifetime: 60000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

  dbadminWrite:
    datasource:
      hikari:
        jdbc-url: jdbc:mysql://production-rds-admin.cluster-cghtjgokrsze.ap-northeast-2.rds.amazonaws.com:56375?&autoReconnect=true&verifyServerCertificate=false&useSSL=false
        username: admin-base
        password: lunaAdminBase201906!
        driverClassName: com.mysql.cj.jdbc.Driver
        maximum-pool-size: 30
        #minimum-idle: 100
        max-lifetime: 60000 #1800000
        connection-timeout: 30000 #30000
        validation-timeout: 5000
        #connection-test-query: SELECT 1
        data-source-properties:
          cachePrepStmts: true
          prepStmtCacheSize: 250
          prepStmtCacheSqlLimit: 2048
          useServerPrepStmts: true

---

spring:
  profiles: redislocal
  redis:
    host: dev-redis.eehi9l.0001.apn2.cache.amazonaws.com
    port: 6379
    timeout: 2000

---

spring:
  profiles: redisReal
  redis:
    host: production-ladmin.eehi9l.0001.apn2.cache.amazonaws.com
    port: 6379
    timeout: 2000


---
spring:
  profiles: adminlocal
  boot:
    admin:
      client:
         url: http://localhost:9090


---
spring:
  profiles: tomcatlocal

server:
  port: 8080

  tomcat:
    accesslog:
      enabled: true
      prefix: access_log_ladmin-api
      pattern: "[%A] [%v] [%{yyyy-MM-dd HH:mm:ss}t]  [%a] [%h] [%S] [accesslog] [%m] [%r] [%{User-Agent}i]"
    basedir: E:\logs

---
spring:
  profiles: tomcatReal

server:
  port: 80

  tomcat:
    accesslog:
      enabled: true
      prefix: access_log_ladmin-api
      pattern: "[%A] [%v] [%{yyyy-MM-dd HH:mm:ss}t]  [%a] [%h] [%S] [accesslog] [%m] [%r] [%{User-Agent}i]"
    basedir: /tomcat/
