export const USER = 'USER'
export const USER_MENU_MAIN = 'USER_MENU_MAIN'
export const USER_MENU_SUB = 'USER_MENU_SUB'
export const ERROR_STATE = 'ERROR_STATE'
export const IS_AUTH = 'IS_AUTH'
export const ROUTE_PROPS = 'ROUTE_PROPS'
